### ISSUE TITLE
Python3 compatibility is broken

### ISSUE THREAD

**Issue by ayalash** [Infinidat/infi.pyvmomi_wrapper#10]
Commit https://github.com/Infinidat/infi.pyvmomi_wrapper/commit/3faff0eccd7671a98a1f0dfb8ef46c4689d88fc4 added implicit relative import within the package - This is not allowed in python3.

**Comment by ayalash** [comment]
@wiggin15  Can you please release hotfix with your commit?

**Comment by wiggin15** [comment]
Done
