### ISSUE TITLE
How do you provide the certificate to vasaproviderspec ? 

### ISSUE THREAD

**Issue by Udayan12167** [Infinidat/infi.pyvmomi_wrapper#2]

**Comment by wiggin15** [comment]
Something like this:

```
cert = open("cert.pem").read()
vps = sms.VasaProviderSpec(username=username, password=password, url=url, name=name,
    certificate=cert)
```

A pem file is generated by OpenSSL and it looks like this: https://github.com/sorin-ionescu/dotfiles/blob/master/mercurial/cacerts/dummy-cert.pem

**Comment by Udayan12167** [comment]
I'll try it out. Thanks for the quick response :)

**Comment by Udayan12167** [comment]
What if its a .crt file that i have? Should i convert it to a .pem or will that also do?

**Comment by wiggin15** [comment]
I never tried so I'm not sure. Try it and let me know :)

**Comment by wiggin15** [comment]
Closing this issue, I think it is answered.
