### ISSUE TITLE
Cannot import sms from pyvmomi?

### ISSUE THREAD

**Issue by Udayan12167** [Infinidat/infi.pyvmomi_wrapper#3]
I'm trying to use this but cant import sms from pyvmomi

**Comment by wiggin15** [comment]
First, the import of SMS should be from infi.pyvmomi_wrapper and not pyvmomi, see example here:
https://github.com/Infinidat/infi.pyvmomi_wrapper/blob/develop/src/infi/pyvmomi_wrapper/sms/README.md

Second, the latest version of pyvmomi (5.5.0.2014.1.1) still doesn't support our Sms Client - I'm waiting for them to pull https://github.com/vmware/pyvmomi/pull/165. If you want to use the sms client I'm afraid you'll have to use our fork of pyvmomi too in the meantime, which is ahead by a few commits. You can get it here: https://github.com/Infinidat/pyvmomi.

**Comment by wiggin15** [comment]
Hi. Any news? Can I close this issue?

**Comment by wiggin15** [comment]
The latest code of pyvmomi contains the sms objects and infi.pyvmomi_wrapper is updated accordingly.
