### ISSUE TITLE
about install infi.pyvmomi_wrapper

### ISSUE THREAD

**Issue by jielaidexingfu** [Infinidat/infi.pyvmomi_wrapper#7]
can i install infi.pyvmomi_wrapper without using pip install or easy_install
because i can't connetc to pypi server
can i intsall offline

**Comment by wiggin15** [comment]
Hello @jielaidexingfu .

To run offline installations of Python packages, you can download the latest [source distribution](https://pypi.python.org/packages/e0/71/ab833398795cfacd2aa0acff2f94db7881a079e9965586cf03f55b3ffe77/infi.pyvmomi_wrapper-0.1.19.tar.gz#md5=93a1b2bbce8d847f02537054b3066f64) file, transfer it to your machine and extract it, and then run `python setup.py install` in the extracted directory.
