### ISSUE TITLE
Know existing storage provider 

### ISSUE THREAD

**Issue by shyamachilles** [Infinidat/infi.pyvmomi_wrapper#8]
How do we know of existing/ registered storage providers on the vCenter ? And ensure they are active/ online before creating VVOL datastore.

**Comment by wiggin15** [comment]
Hi @shyamachilles . There is an example of how to use the SMS provider and query for storage providers here:
https://github.com/Infinidat/infi.pyvmomi_wrapper/blob/develop/src/infi/pyvmomi_wrapper/sms/README.md
The use of the API itself is in the SMS API docs: https://code.vmware.com/web/dp/explorer-apis?id=35

**Comment by shyamachilles** [comment]
Thank you @wiggin15
