### ISSUE TITLE
Mount datastore to additional ESX hosts

### ISSUE THREAD

**Issue by shyamachilles** [Infinidat/infi.pyvmomi_wrapper#9]
Could someone please let me know how to mount a VVOL datastore to additional ESXi hosts apart from the one with which it was created.

**Comment by shyamachilles** [comment]
@wiggin15 , could you please help.

**Comment by wiggin15** [comment]
@shyamachilles  I'm afraid I can't help you. This issue tracker is about the infi.pyvmomi_wrapper project and not the address for general questions about the VMware API.
